### ISSUE TITLE
SPIKE: 主機掃描工具

### ISSUE THREAD

**Issue by H1s0kaaa** [Willypai/devopsProject#18]

**Comment by uhong0307** [comment]
目前有找到openVAS, Nmap兩種掃描工具使用, 以openVAS為優先測試對象

**Comment by uhong0307** [comment]
openVAS測試無法連線至greenbone的伺服器，狀況無法排除
![螢幕擷取畫面 2023-12-14 221505](https://github.com/Willypai/devopsProject/assets/144095120/71f1d010-994f-4194-8876-0e3e41b14a8a)

**Comment by uhong0307** [comment]
使用Nmap掃描project也無法掃描到，推測是Nmap無法對URL進行掃描
![螢幕擷取畫面 2023-12-14 221733](https://github.com/Willypai/devopsProject/assets/144095120/72491ee1-4f75-43d8-ad15-7e4777f3aaed)

**Comment by uhong0307** [comment]
對github主機做為測試對象得到Ping掃描、DNS解析和SYN Stealth等資訊
![螢幕擷取畫面 2023-12-14 221733](https://github.com/Willypai/devopsProject/assets/144095120/fde74113-8d7d-446b-82bb-beb40627c955)
